# Generated by Django 5.2.17 on 2026-09-26 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip')], default='ONE_WAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='outstation_type',
            field=models.CharField(blank=True, default='ONE_WAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR_CAB', 'Rovexa Car Cab (4+ Seats)'), ('AUTO', 'Auto Rickshaw'), ('MINI', 'Mini / Hatchback'), ('SEDAN', 'Prime Sedan'), ('SUV', 'Suv / Innova'), ('LUXURY', 'Luxury'), ('PREMIUM', 'Premium')], default='MINI', max_length=50),
        ),
    ]
