# Generated by Django 5.2.17 on 2026-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_driver_booking_passenger_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
